name: Build Desktop Apps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || pip install pyinstaller python-docx pillow requests

    - name: Empacotar com PyInstaller
      run: |
        pyinstaller --onefile --windowed --name "GeradorProvas" gerador_provas_completo.py

    - name: Upload do executável
      uses: actions/upload-artifact@v4
      with:
        name: GeradorProvas-${{ matrix.os }}
        path: dist/*
